name: Linter
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  golangci:
    name: Linting Go code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633               # v4.1.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82d40c283aeb1f2b6595839195e95c2d6a49081b  # v5.0.0
        with:
          version: latest
